/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdvisorContext {
  'vertical' : [] | [string],
  'sessionHistory' : [] | [Array<SessionMessage>],
  'product' : [] | [string],
}
export interface AdvisorResponse {
  'nextSteps' : Array<string>,
  'useCaseSummary' : string,
  'recommendedInstruments' : Array<string>,
  'rawResponse' : string,
  'recommendedProduct' : string,
}
export interface ChatMessage {
  'content' : string,
  'role' : string,
  'timestamp' : Timestamp,
}
export interface ChatSession {
  'id' : string,
  'messages' : Array<ChatMessage>,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
}
export interface CourseModule {
  'labExercises' : Array<string>,
  'moduleName' : string,
  'objectives' : Array<string>,
}
export interface CourseOutline {
  'title' : string,
  'fullMarkdown' : string,
  'modules' : Array<CourseModule>,
}
export interface GeneratedMaterial {
  'id' : string,
  'title' : string,
  'content' : string,
  'kind' : string,
  'createdAt' : Timestamp,
}
export interface HttpHeader { 'value' : string, 'name' : string }
export interface HttpRequestResult {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<HttpHeader>,
}
export interface IndustryVertical {
  'id' : string,
  'solutionMappings' : Array<SolutionMapping>,
  'name' : string,
  'overview' : string,
  'painAreas' : Array<string>,
}
export interface Presentation {
  'title' : string,
  'talkingPointsSummary' : string,
  'slides' : Array<Slide>,
}
export interface Product {
  'id' : string,
  'useCases' : Array<string>,
  'tagline' : string,
  'name' : string,
  'spec' : ProductSpec,
  'instruments' : Array<string>,
}
export interface ProductSpec {
  'voltage' : string,
  'bandwidth' : string,
  'formFactor' : string,
  'connectivity' : string,
  'sampleRate' : string,
  'channels' : bigint,
  'adcBits' : bigint,
}
export interface Schematic {
  'title' : string,
  'asciiDiagram' : string,
  'notes' : string,
  'componentList' : Array<string>,
}
export interface SearchResult {
  'id' : string,
  'title' : string,
  'kind' : string,
  'snippet' : string,
  'score' : bigint,
}
export interface SessionMessage { 'content' : string, 'role' : string }
export interface Slide { 'slideTitle' : string, 'bulletPoints' : Array<string> }
export interface SolutionMapping {
  'painArea' : string,
  'description' : string,
  'instruments' : Array<string>,
  'mokModel' : string,
}
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : HttpRequestResult,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<HttpHeader>,
}
export interface _SERVICE {
  'appendMessage' : ActorMethod<[string, string, string], ChatSession>,
  'deleteSession' : ActorMethod<[string], undefined>,
  'generateCourse' : ActorMethod<[string, [] | [string]], CourseOutline>,
  'generatePresentation' : ActorMethod<[string, string], Presentation>,
  'generateSchematic' : ActorMethod<[string], Schematic>,
  'getAdvisorAdvice' : ActorMethod<[string, AdvisorContext], AdvisorResponse>,
  'getExtendedThinking' : ActorMethod<[], boolean>,
  'getMaterial' : ActorMethod<[string], [] | [GeneratedMaterial]>,
  'getModel' : ActorMethod<[], string>,
  'getProduct' : ActorMethod<[string], [] | [Product]>,
  'getSession' : ActorMethod<[string], [] | [ChatSession]>,
  'getVertical' : ActorMethod<[string], [] | [IndustryVertical]>,
  'listMaterials' : ActorMethod<[], Array<GeneratedMaterial>>,
  'listProducts' : ActorMethod<[], Array<Product>>,
  'listVerticals' : ActorMethod<[], Array<IndustryVertical>>,
  'saveMaterial' : ActorMethod<[string, string, string], GeneratedMaterial>,
  'search' : ActorMethod<[string], Array<SearchResult>>,
  'setApiKey' : ActorMethod<[string], undefined>,
  'setExtendedThinking' : ActorMethod<[boolean], undefined>,
  'setModel' : ActorMethod<[string], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];