/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Timestamp = IDL.Int;
export const ChatMessage = IDL.Record({
  'content' : IDL.Text,
  'role' : IDL.Text,
  'timestamp' : Timestamp,
});
export const ChatSession = IDL.Record({
  'id' : IDL.Text,
  'messages' : IDL.Vec(ChatMessage),
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
});
export const CourseModule = IDL.Record({
  'labExercises' : IDL.Vec(IDL.Text),
  'moduleName' : IDL.Text,
  'objectives' : IDL.Vec(IDL.Text),
});
export const CourseOutline = IDL.Record({
  'title' : IDL.Text,
  'fullMarkdown' : IDL.Text,
  'modules' : IDL.Vec(CourseModule),
});
export const Slide = IDL.Record({
  'slideTitle' : IDL.Text,
  'bulletPoints' : IDL.Vec(IDL.Text),
});
export const Presentation = IDL.Record({
  'title' : IDL.Text,
  'talkingPointsSummary' : IDL.Text,
  'slides' : IDL.Vec(Slide),
});
export const Schematic = IDL.Record({
  'title' : IDL.Text,
  'asciiDiagram' : IDL.Text,
  'notes' : IDL.Text,
  'componentList' : IDL.Vec(IDL.Text),
});
export const SessionMessage = IDL.Record({
  'content' : IDL.Text,
  'role' : IDL.Text,
});
export const AdvisorContext = IDL.Record({
  'vertical' : IDL.Opt(IDL.Text),
  'sessionHistory' : IDL.Opt(IDL.Vec(SessionMessage)),
  'product' : IDL.Opt(IDL.Text),
});
export const AdvisorResponse = IDL.Record({
  'nextSteps' : IDL.Vec(IDL.Text),
  'useCaseSummary' : IDL.Text,
  'recommendedInstruments' : IDL.Vec(IDL.Text),
  'rawResponse' : IDL.Text,
  'recommendedProduct' : IDL.Text,
});
export const GeneratedMaterial = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'kind' : IDL.Text,
  'createdAt' : Timestamp,
});
export const ProductSpec = IDL.Record({
  'voltage' : IDL.Text,
  'bandwidth' : IDL.Text,
  'formFactor' : IDL.Text,
  'connectivity' : IDL.Text,
  'sampleRate' : IDL.Text,
  'channels' : IDL.Nat,
  'adcBits' : IDL.Nat,
});
export const Product = IDL.Record({
  'id' : IDL.Text,
  'useCases' : IDL.Vec(IDL.Text),
  'tagline' : IDL.Text,
  'name' : IDL.Text,
  'spec' : ProductSpec,
  'instruments' : IDL.Vec(IDL.Text),
});
export const SolutionMapping = IDL.Record({
  'painArea' : IDL.Text,
  'description' : IDL.Text,
  'instruments' : IDL.Vec(IDL.Text),
  'mokModel' : IDL.Text,
});
export const IndustryVertical = IDL.Record({
  'id' : IDL.Text,
  'solutionMappings' : IDL.Vec(SolutionMapping),
  'name' : IDL.Text,
  'overview' : IDL.Text,
  'painAreas' : IDL.Vec(IDL.Text),
});
export const SearchResult = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'kind' : IDL.Text,
  'snippet' : IDL.Text,
  'score' : IDL.Nat,
});
export const HttpHeader = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
export const HttpRequestResult = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(HttpHeader),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : HttpRequestResult,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(HttpHeader),
});

export const idlService = IDL.Service({
  'appendMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [ChatSession], []),
  'deleteSession' : IDL.Func([IDL.Text], [], []),
  'generateCourse' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text)],
      [CourseOutline],
      [],
    ),
  'generatePresentation' : IDL.Func([IDL.Text, IDL.Text], [Presentation], []),
  'generateSchematic' : IDL.Func([IDL.Text], [Schematic], []),
  'getAdvisorAdvice' : IDL.Func(
      [IDL.Text, AdvisorContext],
      [AdvisorResponse],
      [],
    ),
  'getExtendedThinking' : IDL.Func([], [IDL.Bool], ['query']),
  'getMaterial' : IDL.Func([IDL.Text], [IDL.Opt(GeneratedMaterial)], ['query']),
  'getModel' : IDL.Func([], [IDL.Text], ['query']),
  'getProduct' : IDL.Func([IDL.Text], [IDL.Opt(Product)], ['query']),
  'getSession' : IDL.Func([IDL.Text], [IDL.Opt(ChatSession)], ['query']),
  'getVertical' : IDL.Func([IDL.Text], [IDL.Opt(IndustryVertical)], ['query']),
  'listMaterials' : IDL.Func([], [IDL.Vec(GeneratedMaterial)], ['query']),
  'listProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'listVerticals' : IDL.Func([], [IDL.Vec(IndustryVertical)], ['query']),
  'saveMaterial' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [GeneratedMaterial],
      [],
    ),
  'search' : IDL.Func([IDL.Text], [IDL.Vec(SearchResult)], ['query']),
  'setApiKey' : IDL.Func([IDL.Text], [], []),
  'setExtendedThinking' : IDL.Func([IDL.Bool], [], []),
  'setModel' : IDL.Func([IDL.Text], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Timestamp = IDL.Int;
  const ChatMessage = IDL.Record({
    'content' : IDL.Text,
    'role' : IDL.Text,
    'timestamp' : Timestamp,
  });
  const ChatSession = IDL.Record({
    'id' : IDL.Text,
    'messages' : IDL.Vec(ChatMessage),
    'createdAt' : Timestamp,
    'updatedAt' : Timestamp,
  });
  const CourseModule = IDL.Record({
    'labExercises' : IDL.Vec(IDL.Text),
    'moduleName' : IDL.Text,
    'objectives' : IDL.Vec(IDL.Text),
  });
  const CourseOutline = IDL.Record({
    'title' : IDL.Text,
    'fullMarkdown' : IDL.Text,
    'modules' : IDL.Vec(CourseModule),
  });
  const Slide = IDL.Record({
    'slideTitle' : IDL.Text,
    'bulletPoints' : IDL.Vec(IDL.Text),
  });
  const Presentation = IDL.Record({
    'title' : IDL.Text,
    'talkingPointsSummary' : IDL.Text,
    'slides' : IDL.Vec(Slide),
  });
  const Schematic = IDL.Record({
    'title' : IDL.Text,
    'asciiDiagram' : IDL.Text,
    'notes' : IDL.Text,
    'componentList' : IDL.Vec(IDL.Text),
  });
  const SessionMessage = IDL.Record({
    'content' : IDL.Text,
    'role' : IDL.Text,
  });
  const AdvisorContext = IDL.Record({
    'vertical' : IDL.Opt(IDL.Text),
    'sessionHistory' : IDL.Opt(IDL.Vec(SessionMessage)),
    'product' : IDL.Opt(IDL.Text),
  });
  const AdvisorResponse = IDL.Record({
    'nextSteps' : IDL.Vec(IDL.Text),
    'useCaseSummary' : IDL.Text,
    'recommendedInstruments' : IDL.Vec(IDL.Text),
    'rawResponse' : IDL.Text,
    'recommendedProduct' : IDL.Text,
  });
  const GeneratedMaterial = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'kind' : IDL.Text,
    'createdAt' : Timestamp,
  });
  const ProductSpec = IDL.Record({
    'voltage' : IDL.Text,
    'bandwidth' : IDL.Text,
    'formFactor' : IDL.Text,
    'connectivity' : IDL.Text,
    'sampleRate' : IDL.Text,
    'channels' : IDL.Nat,
    'adcBits' : IDL.Nat,
  });
  const Product = IDL.Record({
    'id' : IDL.Text,
    'useCases' : IDL.Vec(IDL.Text),
    'tagline' : IDL.Text,
    'name' : IDL.Text,
    'spec' : ProductSpec,
    'instruments' : IDL.Vec(IDL.Text),
  });
  const SolutionMapping = IDL.Record({
    'painArea' : IDL.Text,
    'description' : IDL.Text,
    'instruments' : IDL.Vec(IDL.Text),
    'mokModel' : IDL.Text,
  });
  const IndustryVertical = IDL.Record({
    'id' : IDL.Text,
    'solutionMappings' : IDL.Vec(SolutionMapping),
    'name' : IDL.Text,
    'overview' : IDL.Text,
    'painAreas' : IDL.Vec(IDL.Text),
  });
  const SearchResult = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'kind' : IDL.Text,
    'snippet' : IDL.Text,
    'score' : IDL.Nat,
  });
  const HttpHeader = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const HttpRequestResult = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(HttpHeader),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : HttpRequestResult,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(HttpHeader),
  });
  
  return IDL.Service({
    'appendMessage' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [ChatSession],
        [],
      ),
    'deleteSession' : IDL.Func([IDL.Text], [], []),
    'generateCourse' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text)],
        [CourseOutline],
        [],
      ),
    'generatePresentation' : IDL.Func([IDL.Text, IDL.Text], [Presentation], []),
    'generateSchematic' : IDL.Func([IDL.Text], [Schematic], []),
    'getAdvisorAdvice' : IDL.Func(
        [IDL.Text, AdvisorContext],
        [AdvisorResponse],
        [],
      ),
    'getExtendedThinking' : IDL.Func([], [IDL.Bool], ['query']),
    'getMaterial' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(GeneratedMaterial)],
        ['query'],
      ),
    'getModel' : IDL.Func([], [IDL.Text], ['query']),
    'getProduct' : IDL.Func([IDL.Text], [IDL.Opt(Product)], ['query']),
    'getSession' : IDL.Func([IDL.Text], [IDL.Opt(ChatSession)], ['query']),
    'getVertical' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IndustryVertical)],
        ['query'],
      ),
    'listMaterials' : IDL.Func([], [IDL.Vec(GeneratedMaterial)], ['query']),
    'listProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'listVerticals' : IDL.Func([], [IDL.Vec(IndustryVertical)], ['query']),
    'saveMaterial' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [GeneratedMaterial],
        [],
      ),
    'search' : IDL.Func([IDL.Text], [IDL.Vec(SearchResult)], ['query']),
    'setApiKey' : IDL.Func([IDL.Text], [], []),
    'setExtendedThinking' : IDL.Func([IDL.Bool], [], []),
    'setModel' : IDL.Func([IDL.Text], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };