/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Slide {
    slideTitle: string;
    bulletPoints: Array<string>;
}
export type Timestamp = bigint;
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<HttpHeader>;
}
export interface SolutionMapping {
    painArea: string;
    description: string;
    instruments: Array<string>;
    mokModel: string;
}
export interface SearchResult {
    id: string;
    title: string;
    kind: string;
    snippet: string;
    score: bigint;
}
export interface Schematic {
    title: string;
    asciiDiagram: string;
    notes: string;
    componentList: Array<string>;
}
export interface IndustryVertical {
    id: string;
    solutionMappings: Array<SolutionMapping>;
    name: string;
    overview: string;
    painAreas: Array<string>;
}
export interface HttpRequestResult {
    status: bigint;
    body: Uint8Array;
    headers: Array<HttpHeader>;
}
export interface GeneratedMaterial {
    id: string;
    title: string;
    content: string;
    kind: string;
    createdAt: Timestamp;
}
export interface Presentation {
    title: string;
    talkingPointsSummary: string;
    slides: Array<Slide>;
}
export interface AdvisorContext {
    vertical?: string;
    sessionHistory?: Array<SessionMessage>;
    product?: string;
}
export interface HttpHeader {
    value: string;
    name: string;
}
export interface ProductSpec {
    voltage: string;
    bandwidth: string;
    formFactor: string;
    connectivity: string;
    sampleRate: string;
    channels: bigint;
    adcBits: bigint;
}
export interface SessionMessage {
    content: string;
    role: string;
}
export interface CourseModule {
    labExercises: Array<string>;
    moduleName: string;
    objectives: Array<string>;
}
export interface ChatSession {
    id: string;
    messages: Array<ChatMessage>;
    createdAt: Timestamp;
    updatedAt: Timestamp;
}
export interface AdvisorResponse {
    nextSteps: Array<string>;
    useCaseSummary: string;
    recommendedInstruments: Array<string>;
    rawResponse: string;
    recommendedProduct: string;
}
export interface TransformationInput {
    context: Uint8Array;
    response: HttpRequestResult;
}
export interface CourseOutline {
    title: string;
    fullMarkdown: string;
    modules: Array<CourseModule>;
}
export interface ChatMessage {
    content: string;
    role: string;
    timestamp: Timestamp;
}
export interface Product {
    id: string;
    useCases: Array<string>;
    tagline: string;
    name: string;
    spec: ProductSpec;
    instruments: Array<string>;
}
export interface backendInterface {
    appendMessage(sessionId: string, role: string, content: string): Promise<ChatSession>;
    deleteSession(sessionId: string): Promise<void>;
    generateCourse(vertical: string, product: string | null): Promise<CourseOutline>;
    generatePresentation(vertical: string, product: string): Promise<Presentation>;
    generateSchematic(useCaseDescription: string): Promise<Schematic>;
    getAdvisorAdvice(userQuery: string, context: AdvisorContext): Promise<AdvisorResponse>;
    getExtendedThinking(): Promise<boolean>;
    getMaterial(id: string): Promise<GeneratedMaterial | null>;
    getModel(): Promise<string>;
    getProduct(id: string): Promise<Product | null>;
    getSession(sessionId: string): Promise<ChatSession | null>;
    getVertical(id: string): Promise<IndustryVertical | null>;
    listMaterials(): Promise<Array<GeneratedMaterial>>;
    listProducts(): Promise<Array<Product>>;
    listVerticals(): Promise<Array<IndustryVertical>>;
    saveMaterial(kind: string, title: string, content: string): Promise<GeneratedMaterial>;
    search(term: string): Promise<Array<SearchResult>>;
    setApiKey(key: string): Promise<void>;
    setExtendedThinking(enabled: boolean): Promise<void>;
    setModel(model: string): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
}
import type { AdvisorContext as _AdvisorContext, ChatSession as _ChatSession, GeneratedMaterial as _GeneratedMaterial, IndustryVertical as _IndustryVertical, Product as _Product, SessionMessage as _SessionMessage } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async appendMessage(arg0: string, arg1: string, arg2: string): Promise<ChatSession> {
        if (this.processError) {
            try {
                const result = await this.actor.appendMessage(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.appendMessage(arg0, arg1, arg2);
            return result;
        }
    }
    async deleteSession(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSession(arg0);
            return result;
        }
    }
    async generateCourse(arg0: string, arg1: string | null): Promise<CourseOutline> {
        if (this.processError) {
            try {
                const result = await this.actor.generateCourse(arg0, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateCourse(arg0, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async generatePresentation(arg0: string, arg1: string): Promise<Presentation> {
        if (this.processError) {
            try {
                const result = await this.actor.generatePresentation(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generatePresentation(arg0, arg1);
            return result;
        }
    }
    async generateSchematic(arg0: string): Promise<Schematic> {
        if (this.processError) {
            try {
                const result = await this.actor.generateSchematic(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateSchematic(arg0);
            return result;
        }
    }
    async getAdvisorAdvice(arg0: string, arg1: AdvisorContext): Promise<AdvisorResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdvisorAdvice(arg0, to_candid_AdvisorContext_n2(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdvisorAdvice(arg0, to_candid_AdvisorContext_n2(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getExtendedThinking(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.getExtendedThinking();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExtendedThinking();
            return result;
        }
    }
    async getMaterial(arg0: string): Promise<GeneratedMaterial | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMaterial(arg0);
                return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMaterial(arg0);
            return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getModel(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getModel();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getModel();
            return result;
        }
    }
    async getProduct(arg0: string): Promise<Product | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProduct(arg0);
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProduct(arg0);
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSession(arg0: string): Promise<ChatSession | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSession(arg0);
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSession(arg0);
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVertical(arg0: string): Promise<IndustryVertical | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getVertical(arg0);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVertical(arg0);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMaterials(): Promise<Array<GeneratedMaterial>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMaterials();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMaterials();
            return result;
        }
    }
    async listProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.listProducts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listProducts();
            return result;
        }
    }
    async listVerticals(): Promise<Array<IndustryVertical>> {
        if (this.processError) {
            try {
                const result = await this.actor.listVerticals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listVerticals();
            return result;
        }
    }
    async saveMaterial(arg0: string, arg1: string, arg2: string): Promise<GeneratedMaterial> {
        if (this.processError) {
            try {
                const result = await this.actor.saveMaterial(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveMaterial(arg0, arg1, arg2);
            return result;
        }
    }
    async search(arg0: string): Promise<Array<SearchResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.search(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.search(arg0);
            return result;
        }
    }
    async setApiKey(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setApiKey(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setApiKey(arg0);
            return result;
        }
    }
    async setExtendedThinking(arg0: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setExtendedThinking(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setExtendedThinking(arg0);
            return result;
        }
    }
    async setModel(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setModel(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setModel(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_GeneratedMaterial]): GeneratedMaterial | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Product]): Product | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ChatSession]): ChatSession | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_IndustryVertical]): IndustryVertical | null {
    return value.length === 0 ? null : value[0];
}
function to_candid_AdvisorContext_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AdvisorContext): _AdvisorContext {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    vertical?: string;
    sessionHistory?: Array<SessionMessage>;
    product?: string;
}): {
    vertical: [] | [string];
    sessionHistory: [] | [Array<_SessionMessage>];
    product: [] | [string];
} {
    return {
        vertical: value.vertical ? candid_some(value.vertical) : candid_none(),
        sessionHistory: value.sessionHistory ? candid_some(value.sessionHistory) : candid_none(),
        product: value.product ? candid_some(value.product) : candid_none()
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
